#!/usr/bin/env bash
# install nginx server
# Update package list
apt-get -y update

# Install Nginx
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# Restart Nginx without using systemctl
service nginx restart
