#!/usr/bin/env bash
# This script installs an nginx server & customize http return header

# Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(348313-web-01)

# Configure Nginx to add custom HTTP header
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply changes using SysV init
sudo /etc/init.d/nginx restart
