#!/usr/bin/env bash
# A script that sets up and configures HAproxy on your lb-01 server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

echo "

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 348313-web-01 54.197.207.15:80 check
    server 348313-web-02 54.236.56.251:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
