#!/usr/bin/env bash
# This script is for  shell conditionals and loop
a=0
while ((a<10));
do
  if [ $a -eq 3 ]
  then
     echo "bad luck"
  elif [ $a -eq 7 ]
  then
     echo "good luck"
  else
     echo "Best School"
  fi
  ((a++))
done
